# -*- coding: utf-8 -*-
"""Copy of week1_LUNAVATH SANGEETHA1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12esA_AkQyqq4PzbvHT1dZVpbS0NWELmi

# 📘 Week 1 Assignment — ML Foundations

**Topics Covered:** Python · NumPy · Pandas · Linear Algebra · Statistics · Probability Theory

---

> Complete all cells. Where marked `# YOUR CODE HERE`, write your solution. Do not change cell types or remove assertion blocks.
"""

# ── Setup ──────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from io import StringIO

plt.rcParams['figure.figsize'] = (9, 4)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
print('All imports OK ✓')

"""---
## Part 1 — Python Fundamentals

### 1.1 Data Types & Control Flow

Write a function `classify_number(n)` that:
- Returns `"negative"` if `n < 0`
- Returns `"zero"` if `n == 0`
- Returns `"small positive"` if `0 < n <= 10`
- Returns `"large positive"` otherwise
"""

def classify_number(n):
    if n < 0:
        return "negative"
    elif n == 0:
        return "zero"
    elif n <= 10:
        return "small positive"
    else:
        return "large positive"

# Tests
assert classify_number(-5) == "negative"
assert classify_number(0)  == "zero"
assert classify_number(7)  == "small positive"
assert classify_number(42) == "large positive"
print("1.1 passed ✓")

"""### 1.2 Data Structures

Given the list `words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']`:

1. Build a **dict** `word_count` mapping each word to its frequency using only a loop (no `Counter`).
2. Using a **set**, find all unique words and store in `unique_words`.
3. Using a **list comprehension**, build `long_words` containing words with more than 5 characters.
"""

words = ['apple', 'banana', 'cherry', 'apple', 'date', 'banana', 'apple']

# 1. word_count dict
word_count = {}
for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

# 2. unique_words set
unique_words = set(words)

# 3. long_words list comprehension
long_words = [word for word in words if len(word) > 5]

# Tests
assert word_count == {'apple': 3, 'banana': 2, 'cherry': 1, 'date': 1}
assert unique_words == {'apple', 'banana', 'cherry', 'date'}
assert set(long_words) == {'banana', 'cherry'}
print("1.2 passed ✓")

"""### 1.3 Exceptions

Write `safe_divide(a, b)` that:
- Returns `a / b` normally
- Returns `None` if `b == 0` (catch `ZeroDivisionError`)
- Raises `TypeError` with message `"Inputs must be numeric"` if either input is not a number
"""

def safe_divide(a, b):
    if not isinstance(a, (int, float)) or not isinstance(b, (int, float)):
        raise TypeError("Inputs must be numeric")

    try:
        return a / b
    except ZeroDivisionError:
        return None

# Tests
assert safe_divide(10, 2) == 5.0
assert safe_divide(5, 0) is None

try:
    safe_divide('x', 2)
    assert False, "Should have raised TypeError"
except TypeError as e:
    assert str(e) == "Inputs must be numeric"

print("1.3 passed ✓")

"""### 1.4 Functions & Lambdas

1. Write a function `apply_twice(f, x)` that applies function `f` to `x` twice: `f(f(x))`.
2. Using a **lambda**, create `triple` that multiplies its input by 3.
3. Demonstrate: `apply_twice(triple, 4)` should return `36`.
"""

def apply_twice(f, x):
    return f(f(x))

triple = lambda x: x * 3

result = apply_twice(triple, 4)

assert result == 36, f"Expected 36, got {result}"
print("1.4 passed ✓")

"""---
## Part 2 — NumPy

### 2.1 Array Creation & Shapes

1. Create a 1D array `arr1d` of integers 0–11.
2. Reshape it into a 2D array `arr2d` of shape `(3, 4)`.
3. Reshape `arr1d` into a 3D array `arr3d` of shape `(2, 2, 3)`.
4. Print the shape, ndim, and dtype of each.
"""

import numpy as np

# 1. Create a 1D array of integers 0–11
arr1d = np.arange(12)

# 2. Reshape into a 2D array of shape (3, 4)
arr2d = arr1d.reshape(3, 4)

# 3. Reshape into a 3D array of shape (2, 2, 3)
arr3d = arr1d.reshape(2, 2, 3)

# 4. Print shape, ndim, and dtype of each
for name, arr in [("arr1d", arr1d), ("arr2d", arr2d), ("arr3d", arr3d)]:
    print(f"{name}:")
    print(f"  shape = {arr.shape}")
    print(f"  ndim  = {arr.ndim}")
    print(f"  dtype = {arr.dtype}")
    print()

# Tests
assert arr1d.shape == (12,)
assert arr2d.shape == (3, 4)
assert arr3d.shape == (2, 2, 3)

print("2.1 passed ✓")
print(f"arr2d:\n{arr2d}")
print(f"arr3d:\n{arr3d}")

"""### 2.2 Indexing & Slicing

Using `arr2d` from above:
1. Extract the **second row** → `row2`
2. Extract the **third column** → `col3`
3. Extract the **bottom-right 2×2 submatrix** → `sub`
4. Use **boolean indexing** to get all elements greater than 7 → `gt7`
"""

# 1. Second row
row2 = arr2d[1]

# 2. Third column
col3 = arr2d[:, 2]

# 3. Bottom-right 2×2 submatrix
sub = arr2d[1:, 2:]

# 4. Boolean indexing: elements greater than 7
gt7 = arr2d[arr2d > 7]

# Tests
assert list(row2) == [4, 5, 6, 7]
assert list(col3) == [2, 6, 10]
assert sub.shape == (2, 2)
assert list(gt7) == [8, 9, 10, 11]

print("2.2 passed ✓")

"""### 2.3 Operations & Dot Product

Given:
```
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]
```

1. Compute **element-wise product** `C = A * B`
2. Compute **matrix multiplication** `D = A @ B`
3. Compute the **dot product** of vectors `[1,2,3]` and `[4,5,6]` → `dp`
4. Multiply all elements of `A` by scalar 3 → `E`
"""

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 1. Element-wise product
C = A * B

# 2. Matrix multiplication
D = A @ B

# 3. Dot product of vectors
dp = np.dot([1, 2, 3], [4, 5, 6])

# 4. Scalar multiplication
E = A * 3

# Tests
assert np.array_equal(C, [[5,12],[21,32]])
assert np.array_equal(D, [[19,22],[43,50]])
assert dp == 32
assert np.array_equal(E, [[3,6],[9,12]])

print("2.3 passed ✓")

"""---
## Part 3 — Pandas
"""

import pandas as pd
from io import StringIO

CSV_DATA = """employee_id,name,department,salary,age,years_exp,performance
1,Alice,Engineering,95000,30,5,4.2
2,Bob,Marketing,72000,35,8,3.8
3,Carol,Engineering,88000,28,3,4.5
4,Dave,HR,61000,42,15,3.1
5,Eve,Engineering,102000,38,12,4.8
6,Frank,Marketing,68000,29,4,3.5
7,Grace,HR,,31,6,3.9
8,Hank,Engineering,91000,45,20,4.1
9,Iris,Marketing,75000,,7,4.0
10,Jack,Engineering,85000,33,8,
"""

df = pd.read_csv(StringIO(CSV_DATA))
print(f"Shape: {df.shape}")
df.head()

"""### 3.1 DataFrames vs Series

1. Extract the `salary` column as a **Series** → `salary_series`
2. Extract `name` and `department` columns as a **DataFrame** → `name_dept_df`
3. Print the type of each to confirm.
"""

# 1. Extract salary column as a Series
salary_series = df["salary"]

# 2. Extract name and department columns as a DataFrame
name_dept_df = df[["name", "department"]]

# 3. Confirm types
assert isinstance(salary_series, pd.Series)
assert isinstance(name_dept_df, pd.DataFrame)

print(f"salary_series type: {type(salary_series).__name__}")
print(f"name_dept_df type: {type(name_dept_df).__name__}")
print("3.1 passed ✓")

"""### 3.2 iloc & loc

1. Use `iloc` to select rows 2–4 (inclusive), columns 0–2 → `iloc_result`
2. Use `loc` to select rows where index is 5 or 6, columns `name` and `salary` → `loc_result`
"""

# 1. Rows 2–4 (inclusive), columns 0–2 using iloc
iloc_result = df.iloc[2:5, 0:3]

# 2. Rows with index 5 and 6, columns name and salary using loc
loc_result = df.loc[[5, 6], ['name', 'salary']]

assert iloc_result.shape == (3, 3)
assert list(loc_result.columns) == ['name', 'salary']

print("3.2 passed ✓")
display(iloc_result)
display(loc_result)

"""### 3.3 Filtering & Group By

1. Filter employees in **Engineering** with **salary > 90000** → `senior_eng`
2. Group by `department` and compute mean salary and mean performance → `dept_stats`
3. Sort `dept_stats` by mean salary descending.
"""

# 1. Engineering employees with salary > 90000
senior_eng = df[
    (df["department"] == "Engineering") &
    (df["salary"] > 90000)
]

# 2. Group by department and compute mean salary and mean performance
dept_stats = (
    df.groupby("department")
      .agg({
          "salary": "mean",
          "performance": "mean"
      })
      .sort_values(by="salary", ascending=False)
)

print(f"Senior engineers: {len(senior_eng)}")
display(senior_eng[["name", "salary"]])

print("\nDept stats:")
display(dept_stats)

"""### 3.4 Handling Missing Data

1. Identify which columns have missing values and how many → print a summary.
2. Fill missing `salary` with the **median salary** → `df_filled`
3. Fill missing `age` with the **mean age** (rounded to nearest int).
4. Drop rows where `performance` is missing.
5. Confirm no nulls remain.
"""

print("Missing values before:")
print(df.isnull().sum())

df_filled = df.copy()

# 1. Median salary
salary_median = df_filled["salary"].median()
df_filled["salary"] = df_filled["salary"].fillna(salary_median)

# 2. Mean age (rounded to nearest int)
age_mean = round(df_filled["age"].mean())
df_filled["age"] = df_filled["age"].fillna(age_mean)

# 3. Drop rows with missing performance
df_filled = df_filled.dropna(subset=["performance"])

print("\nMissing values after:")
print(df_filled.isnull().sum())

assert df_filled.isnull().sum().sum() == 0, "Still has nulls!"
print("3.4 passed ✓")

"""---
## Part 4 — Linear Algebra

### 4.1 Vectors & Matrices as Data

1. Represent a 2D point `(3, 4)` as a NumPy vector and compute its **L2 norm** (Euclidean length).
2. Create a 3×3 matrix `M` (use any non-trivial values).
3. Plot the vector as an arrow from the origin using `matplotlib` — label axes and title it *"Vector Visualization"*.
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Vector and L2 norm
v = np.array([3, 4])
norm_v = np.linalg.norm(v)

# 2. 3x3 matrix (any non-trivial values)
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 3. Plot the vector
fig, ax = plt.subplots()

# Draw arrow from origin to (3, 4)
ax.quiver(0, 0, v[0], v[1], angles='xy', scale_units='xy', scale=1)

ax.set_xlim(-1, 5)
ax.set_ylim(-1, 5)
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_title('Vector Visualization')
ax.axhline(0, color='k', lw=0.8)
ax.axvline(0, color='k', lw=0.8)

plt.tight_layout()
plt.show()

assert abs(norm_v - 5.0) < 1e-9
assert M.shape == (3, 3)

print(f"4.1 passed ✓  |v| = {norm_v}")

"""### 4.2 Matrix Operations in Practice

Let:
```
P = [[2, 1], [0, 3]]
Q = [[1, 4], [2, 0]]
```

1. Compute `P + Q` (matrix addition)
2. Compute `3 * P` (scalar multiplication)
3. Compute `P @ Q` (matrix multiplication)
4. Verify that matrix multiplication is **not commutative** — show `P @ Q ≠ Q @ P`.
"""

import numpy as np

P = np.array([[2, 1], [0, 3]])
Q = np.array([[1, 4], [2, 0]])

# 1. Matrix addition
PplusQ = P + Q

# 2. Scalar multiplication
scalar3P = 3 * P

# 3. Matrix multiplication
PQ = P @ Q

# 4. Reverse order multiplication
QP = Q @ P

print(f"P + Q =\n{PplusQ}")
print(f"3*P =\n{scalar3P}")
print(f"P @ Q =\n{PQ}")
print(f"Q @ P =\n{QP}")
print(f"PQ == QP? {np.array_equal(PQ, QP)}")

assert not np.array_equal(PQ, QP), "They should differ!"
print("4.2 passed ✓")

"""### 4.3 Eigenvalues & Eigenvectors

For the matrix:
```
A = [[4, 1],
     [2, 3]]
```

1. Compute eigenvalues and eigenvectors using `np.linalg.eig`.
2. **Verify** the eigenvector equation: `A @ v = λ * v` for each eigenpair.
3. Plot both eigenvectors as arrows, scaled by their eigenvalues, on a 2D plot.
4. **Explain** in a markdown cell (below): what does it geometrically mean for a matrix to stretch a vector?
"""

import numpy as np
import matplotlib.pyplot as plt

A = np.array([[4, 1],
              [2, 3]], dtype=float)

# 1. Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print(f"Eigenvalues: {eigenvalues}")
print(f"Eigenvectors (columns):\n{eigenvectors}")

# 2. Verify Av = λv for each eigenpair
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]

    Av = A @ v
    lv = lam * v

    print(f"\nEigenpair {i + 1}:")
    print("A @ v =", Av)
    print("λ * v =", lv)

    assert np.allclose(Av, lv), "Eigenvector equation failed!"

# 3. Plot eigenvectors scaled by eigenvalues
fig, ax = plt.subplots()

for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]

    scaled_v = lam * v

    ax.quiver(
        0, 0,
        scaled_v[0], scaled_v[1],
        angles='xy',
        scale_units='xy',
        scale=1,
        label=f"λ={lam:.2f}"
    )

ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_title("Eigenvectors Scaled by Eigenvalues")
ax.axhline(0, color='k', lw=0.8)
ax.axvline(0, color='k', lw=0.8)
ax.legend()

plt.tight_layout()
plt.show()

print("4.3 passed ✓")

"""A matrix transforms vectors. Most vectors change both direction and length, but an **eigenvector** keeps the same direction (or flips direction) after the transformation.

If

Av = λv

then **v** is an eigenvector and **λ** is its eigenvalue.

- **λ > 1**: the vector is stretched.
- **0 < λ < 1**: the vector is squished (compressed).
- **λ < 0**: the vector is flipped and scaled.

So, eigenvectors are directions that the matrix leaves unchanged, and eigenvalues tell us how much the matrix stretches or squishes along those directions.

### 4.4 SVD & Dimensionality Reduction

1. Create a random 4×3 matrix `X` (use `np.random.seed(42)`).
2. Compute its **SVD**: `U, S, Vt = np.linalg.svd(X, full_matrices=False)`.
3. **Reconstruct** `X` from the SVD and verify it matches the original.
4. Perform a **rank-1 approximation** using only the largest singular value/vector — call it `X_approx`.
5. Explain the relationship between SVD components and PCA in the markdown cell below.
"""

import numpy as np

np.random.seed(42)
X = np.random.randn(4, 3)

# 2. Compute SVD
U, S, Vt = np.linalg.svd(X, full_matrices=False)

# 3. Reconstruct X
X_reconstructed = U @ np.diag(S) @ Vt

# 4. Rank-1 approximation
X_approx = S[0] * np.outer(U[:, 0], Vt[0, :])

print(f"U shape: {U.shape}, S shape: {S.shape}, Vt shape: {Vt.shape}")
print(f"Singular values: {S}")
print(f"Reconstruction error: {np.linalg.norm(X - X_reconstructed):.2e}")
print(f"Rank-1 approximation:\n{X_approx}")

assert np.allclose(X, X_reconstructed, atol=1e-10), "Reconstruction failed!"
print("4.4 passed ✓")

"""In SVD,

X = UΣVᵀ

- **U** contains the left singular vectors (directions in the sample space).
- **S (Σ)** contains the singular values, which measure the importance of each component.
- **Vᵀ** contains the right singular vectors.

For a centered dataset, the **right singular vectors** (rows of Vᵀ, or columns of V) are the **principal components** in PCA.

The directions of maximum variance are therefore contained in **V** (equivalently, the rows of **Vᵀ**). The singular values indicate how much variance is captured along each principal component, with larger singular values corresponding to more explained variance.

---
## Part 5 — Statistics

### 5.1 Descriptive vs Inferential Statistics

Using the cleaned `df_filled` from Part 3:

1. Compute **descriptive statistics** for the `salary` column: mean, median, std, min, max, IQR.
2. Plot a **histogram** of salary with a KDE overlay.
3. In the markdown cell below, write one sentence each defining: *population*, *sample*, *descriptive statistic*, *inferential statistic*.
"""

import numpy as np
import matplotlib.pyplot as plt

salary = df_filled['salary']

# Descriptive statistics
mean_s   = salary.mean()
median_s = salary.median()
std_s    = salary.std()
min_s    = salary.min()
max_s    = salary.max()

q1 = np.percentile(salary, 25)
q3 = np.percentile(salary, 75)
iqr_s = q3 - q1

print(f"Mean:   {mean_s:.0f}")
print(f"Median: {median_s:.0f}")
print(f"Std:    {std_s:.0f}")
print(f"Range:  {min_s:.0f} – {max_s:.0f}")
print(f"IQR:    {iqr_s:.0f}")

# Histogram + KDE
fig, ax = plt.subplots()

salary.plot.hist(bins=6, density=True, ax=ax)
salary.plot.kde(ax=ax)

ax.set_xlabel('Salary')
ax.set_title('Salary Distribution')

plt.tight_layout()
plt.show()

"""- **Population:** The entire group of individuals or observations being studied.
- **Sample:** A subset of the population used to collect and analyze data.
- **Descriptive statistic:** A value that summarizes or describes a dataset (e.g., mean, median, standard deviation).
- **Inferential statistic:** A method used to draw conclusions about a population based on sample data.

### 5.2 Hypothesis Testing

**Scenario:** You suspect that Engineering salaries are significantly higher than the company average.

1. State the **null hypothesis H₀** and **alternative hypothesis H₁**.
2. Run a **one-sample t-test** comparing Engineering salaries against the overall mean salary.
3. Interpret the p-value at α = 0.05.
4. Also compute the **Pearson correlation** between `salary` and `years_exp`, and interpret it.
"""

from scipy import stats

eng_salaries = df_filled[df_filled['department'] == 'Engineering']['salary']
overall_mean = df_filled['salary'].mean()

# One-sample t-test
t_stat, p_value = stats.ttest_1samp(eng_salaries, popmean=overall_mean)

print(f"Overall mean salary: {overall_mean:.0f}")
print(f"Engineering mean salary: {eng_salaries.mean():.0f}")
print(f"t-statistic: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")
print(f"Reject H0 at α=0.05? {p_value < 0.05}")

# Pearson correlation
r, r_pval = stats.pearsonr(
    df_filled['salary'],
    df_filled['years_exp']
)

print(f"\nPearson r (salary vs years_exp): {r:.4f}, p={r_pval:.4f}")

"""- **H₀:** The mean salary of Engineering employees is equal to the overall company mean salary.
- **H₁:** The mean salary of Engineering employees is higher than the overall company mean salary.
- **Conclusion:** If the p-value < 0.05, reject H₀ and conclude that Engineering salaries are significantly higher than the company average. Otherwise, fail to reject H₀ and conclude that there is insufficient evidence to say Engineering salaries are higher.

### 5.3 Error Metrics

Given these predictions and actuals, **implement from scratch** (no sklearn):
- MAE, MSE, RMSE
- R² Score
- Adjusted R² (assume 2 features)
"""

import numpy as np

y_true = np.array([3.0, 5.0, 2.5, 7.0, 4.5, 6.0, 1.5, 8.0])
y_pred = np.array([2.8, 5.2, 2.1, 7.5, 4.0, 6.3, 2.0, 7.8])

n, p = len(y_true), 2

# MAE
mae = np.mean(np.abs(y_true - y_pred))

# MSE
mse = np.mean((y_true - y_pred) ** 2)

# RMSE
rmse = np.sqrt(mse)

# R²
ss_res = np.sum((y_true - y_pred) ** 2)
ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
r2 = 1 - (ss_res / ss_tot)

# Adjusted R²
adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

print(f"MAE:        {mae:.4f}")
print(f"MSE:        {mse:.4f}")
print(f"RMSE:       {rmse:.4f}")
print(f"R²:         {r2:.4f}")
print(f"Adj. R²:    {adj_r2:.4f}")

"""### 5.4 Distribution Testing & Stationarity

1. Generate two samples: `s1` ~ Normal(0, 1), `s2` ~ Exponential(1), both n=200 (seed=0).
2. Run the **Kolmogorov-Smirnov test** (`stats.kstest`) comparing each against a standard normal CDF.
3. Generate a non-stationary time series (linear trend + noise). Run the **Augmented Dickey-Fuller test** (`adfuller` from `statsmodels`) and interpret the result.
4. Difference the series once and re-run ADF to confirm stationarity.
"""

from scipy import stats
from statsmodels.tsa.stattools import adfuller
import numpy as np

np.random.seed(0)

# Generate samples
s1 = np.random.normal(0, 1, 200)
s2 = np.random.exponential(1, 200)

# KS test against standard normal N(0,1)
ks_s1 = stats.kstest(s1, 'norm')
ks_s2 = stats.kstest(s2, 'norm')

print(f"KS test s1 (normal):      stat={ks_s1.statistic:.4f}, p={ks_s1.pvalue:.4f}")
print(f"KS test s2 (exponential): stat={ks_s2.statistic:.4f}, p={ks_s2.pvalue:.4f}")

# Non-stationary time series: trend + noise
t = np.arange(200)
ts = 0.05 * t + np.random.normal(0, 1, 200)

# ADF test
adf_result = adfuller(ts)

print(f"\nADF statistic: {adf_result[0]:.4f}")
print(f"ADF p-value:   {adf_result[1]:.4f}")
print(f"Stationary?    {adf_result[1] < 0.05}")

# Difference once and re-run
ts_diff = np.diff(ts)
adf_diff = adfuller(ts_diff)

print(
    f"\nAfter differencing — p-value: "
    f"{adf_diff[1]:.4f}, Stationary? {adf_diff[1] < 0.05}"
)

"""### 5.5 Model Monitoring Concepts

1. Implement `compute_psi(expected, actual, bins=10)` that computes the **Population Stability Index** between two distributions.
2. Simulate a scenario where a model's input distribution shifts and plot both distributions.
3. In the markdown cell, define: *concept drift*, *covariate drift*, PSI thresholds (what values indicate no/minor/major shift), and one trigger for retraining.
"""

import numpy as np
import matplotlib.pyplot as plt

def compute_psi(expected, actual, bins=10):
    """
    PSI = sum((actual_pct - expected_pct) * ln(actual_pct / expected_pct))
    Add epsilon=1e-10 to avoid log(0).
    """
    epsilon = 1e-10

    # Use expected distribution to define bins
    breakpoints = np.percentile(expected, np.linspace(0, 100, bins + 1))
    breakpoints[0] = -np.inf
    breakpoints[-1] = np.inf

    expected_counts, _ = np.histogram(expected, bins=breakpoints)
    actual_counts, _ = np.histogram(actual, bins=breakpoints)

    expected_pct = expected_counts / len(expected)
    actual_pct = actual_counts / len(actual)

    psi = np.sum(
        (actual_pct - expected_pct)
        * np.log((actual_pct + epsilon) / (expected_pct + epsilon))
    )

    return psi

np.random.seed(1)
train_dist = np.random.normal(50, 10, 1000)    # training distribution
drift_dist = np.random.normal(65, 12, 1000)    # shifted production distribution

psi_value = compute_psi(train_dist, drift_dist)

print(f"PSI: {psi_value:.4f}")
print(
    f"Shift severity: "
    f"{'Major' if psi_value > 0.2 else 'Minor' if psi_value > 0.1 else 'Stable'}"
)

# Plot both distributions
fig, ax = plt.subplots()

ax.hist(train_dist, bins=30, density=True, alpha=0.6, label="Training")
ax.hist(drift_dist, bins=30, density=True, alpha=0.6, label="Production")

ax.legend()
ax.set_title('Distribution Shift Visualization')

plt.tight_layout()
plt.show()

"""- **Concept drift:** The relationship between input features and the target variable changes over time, reducing model accuracy.

- **Covariate drift:** The distribution of input features changes over time, even if the relationship to the target stays the same.

- **PSI < 0.1:** No significant distribution shift; the feature is considered stable.

- **PSI 0.1–0.2:** Moderate shift; monitor the feature and model performance closely.

- **PSI > 0.2:** Major shift; investigate the cause and consider retraining the model.

- **Retraining trigger example:** PSI remains above 0.2 for a key feature or production model performance drops below an acceptable threshold.

---
## Part 6 — Probability Theory

### 6.1 Core Concepts

A bag contains: 4 red, 3 blue, 3 green marbles.

1. Define the sample space and compute P(red), P(blue), P(green).
2. Two marbles drawn **without replacement**. Compute:
   - P(first=red, second=blue) — **joint probability**
   - P(second=blue | first=red) — **conditional probability**
3. Are the two draws **independent**? Show mathematically.
"""

total = 10
red, blue, green = 4, 3, 3

# Single-draw probabilities
p_red = red / total
p_blue = blue / total
p_green = green / total

# Joint probability: P(first=red AND second=blue)
p_red_then_blue = (red / total) * (blue / (total - 1))

# Conditional probability: P(second=blue | first=red)
p_blue_given_red = blue / (total - 1)

# Independence check
independent = (p_blue_given_red == p_blue)

print(f"P(red)={p_red:.3f}, P(blue)={p_blue:.3f}, P(green)={p_green:.3f}")
print(f"P(red,blue): {p_red_then_blue:.4f}")
print(f"P(blue|red): {p_blue_given_red:.4f}")
print(f"P(blue):     {p_blue:.4f}")
print(f"Independent? {independent}")

"""### 6.2 Distributions in the Wild

1. **Normal**: Plot N(μ=0, σ=1) and N(μ=2, σ=0.5) PDFs on the same axes.
2. **Binomial**: A coin is flipped 20 times. Plot the PMF for k=0..20 with p=0.5 and p=0.7.
3. **Poisson**: Average 3 customers/minute. Plot the PMF for k=0..15.
4. For each, write one real-world ML use case in comments.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

# ── Normal ──────────────────────────────────────────────────────────────────
x = np.linspace(-4, 6, 300)

axes[0].plot(x, stats.norm.pdf(x, loc=0, scale=1), label='μ=0, σ=1')
axes[0].plot(x, stats.norm.pdf(x, loc=2, scale=0.5), label='μ=2, σ=0.5')
axes[0].legend()

# ML use case: Modeling residual errors in regression.
axes[0].set_title('Normal Distribution')

# ── Binomial ────────────────────────────────────────────────────────────────
k = np.arange(0, 21)

axes[1].plot(k, stats.binom.pmf(k, n=20, p=0.5), 'o-', label='p=0.5')
axes[1].plot(k, stats.binom.pmf(k, n=20, p=0.7), 's-', label='p=0.7')
axes[1].legend()

# ML use case: Modeling the number of correct predictions in a fixed number of trials.
axes[1].set_title('Binomial Distribution')

# ── Poisson ─────────────────────────────────────────────────────────────────
k2 = np.arange(0, 16)

axes[2].plot(k2, stats.poisson.pmf(k2, mu=3), 'o-')

# ML use case: Modeling counts of events such as clicks, arrivals, or errors per interval.
axes[2].set_title('Poisson Distribution')

plt.tight_layout()
plt.show()

"""### 6.3 Bayes' Theorem

**Scenario — Spam filter:**
- P(Spam) = 0.30 (prior)
- P("free" | Spam) = 0.80 (likelihood)
- P("free" | Not Spam) = 0.05

1. Compute P(Spam | "free") using Bayes' theorem.
2. Implement a simple `naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham)` that returns the posterior P(Spam | word).
3. In the markdown cell, map each term — **prior, likelihood, evidence, posterior** — to the spam example.
"""

p_spam            = 0.30
p_free_given_spam = 0.80
p_free_given_ham  = 0.05
p_ham             = 1 - p_spam

# P(free) — law of total probability
p_free = (
    p_free_given_spam * p_spam
    + p_free_given_ham * p_ham
)

# Bayes
p_spam_given_free = (
    p_free_given_spam * p_spam
) / p_free

print(f"P('free'): {p_free:.4f}")
print(f"P(Spam | 'free'): {p_spam_given_free:.4f}")

def naive_bayes_predict(prior_spam, p_word_given_spam, p_word_given_ham):
    prior_ham = 1 - prior_spam

    evidence = (
        p_word_given_spam * prior_spam
        + p_word_given_ham * prior_ham
    )

    posterior = (
        p_word_given_spam * prior_spam
    ) / evidence

    return posterior

pred = naive_bayes_predict(0.30, 0.80, 0.05)

assert abs(pred - p_spam_given_free) < 1e-9

print(f"naive_bayes_predict: {pred:.4f}")
print("6.3 passed ✓")

"""| Term       | Formula        | In this example                                                                    |
| ---------- | -------------- | ---------------------------------------------------------------------------------- |
| Prior      | P(Spam)        | Probability an email is spam before seeing the word "free" = **0.30**              |
| Likelihood | P(word | Spam) | Probability of seeing "free" given the email is spam = **P("free" | Spam) = 0.80** |
| Evidence   | P(word)        | Overall probability of seeing "free" in any email = **P("free") = 0.275**          |
| Posterior  | P(Spam | word) | Probability the email is spam after seeing "free" = **P(Spam | "free") ≈ 0.8727**  |

### 6.4 Central Limit Theorem

1. Define a population following an **exponential distribution** (λ=1, size=100,000).
2. Repeatedly draw samples of size `n=30` and record their means — do this 5,000 times.
3. Plot the histogram of sample means.
4. Overlay the **theoretical normal distribution** predicted by the CLT: μ = population mean, σ = population_std / sqrt(n).
5. Run a KS test to confirm the distribution of sample means is approximately normal.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

np.random.seed(7)
population = np.random.exponential(scale=1.0, size=100_000)

n_samples = 5000
sample_size = 30

# Draw samples and record their means
sample_means = np.array([
    np.random.choice(population, size=sample_size, replace=True).mean()
    for _ in range(n_samples)
])

pop_mean = population.mean()
pop_std = population.std()

# CLT prediction
clt_std = pop_std / np.sqrt(sample_size)

print(f"Population mean: {pop_mean:.4f}, Population std: {pop_std:.4f}")
print(f"Sample means mean: {sample_means.mean():.4f}, std: {sample_means.std():.4f}")
print(f"CLT predicted std: {clt_std:.4f}")

# Plot histogram + theoretical normal overlay
fig, ax = plt.subplots()

ax.hist(sample_means, bins=40, density=True, alpha=0.7, label='Sample Means')

x = np.linspace(sample_means.min(), sample_means.max(), 300)
ax.plot(
    x,
    stats.norm.pdf(x, loc=pop_mean, scale=clt_std),
    linewidth=2,
    label='CLT Normal Approximation'
)

ax.legend()
ax.set_title('CLT: Distribution of Sample Means')

plt.tight_layout()
plt.show()

# KS test
ks_result = stats.kstest(sample_means, 'norm', args=(pop_mean, clt_std))
print(
    f"KS test p-value: {ks_result.pvalue:.4f} → "
    f"Approximately normal? {ks_result.pvalue > 0.05}"
)

"""The Central Limit Theorem is important because it allows us to approximate the distribution of sample means as normal, even when the underlying data are not normally distributed. This makes it possible to estimate confidence intervals, perform hypothesis tests, and build many statistical models using sample data.

The CLT justifies the common assumption that sampling distributions are approximately normal, which underlies many classical statistical tests such as t-tests, z-tests, and linear regression inference.

---
## 🏁 Submission Checklist

Before submitting, verify:

- [ ] All `assert` blocks pass without errors
- [ ] All `# YOUR CODE HERE` cells are filled
- [ ] All markdown reflection cells are filled in your own words
- [ ] All plots render with labels and titles
- [ ] Notebook runs cleanly from top to bottom (`Kernel → Restart & Run All`)

**Save as:** `week1_<your_name>.ipynb`
"""
