"""
Step 7b: FastAPI application.

Exposes the whole system (RAG + Knowledge Graph + Memory + Agent) as a web
API. Run with:

    uvicorn app.api.main:app --reload

Then open http://127.0.0.1:8000/docs for interactive API documentation
(automatically generated by FastAPI).
"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles

from app.agent.build_agent import run_agent_full
from app.api.schemas import ChatRequest, ChatResponse, KgResult, MemoryResponse, RagResult
from app.graph.query_graph import query_entity
from app.memory.memory_store import get_preferences, get_recent_history
from app.rag.retriever import retrieve

app = FastAPI(
    title="Memory-Augmented Chatbot API",
    description=(
        "RAG + Knowledge Graph + Long-Term Memory + LangGraph agent, "
        "exposed as a web API."
    ),
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health")
def health_check():
    """Simple liveness check."""
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """Send a message to the agent and get a response.
    This runs the full pipeline: memory -> RAG -> knowledge graph ->
    tool routing (if needed) -> generation -> save to memory.

    Also reports which subsystems actually contributed to this answer,
    reflecting the real LangGraph routing decision for this turn.
    """
    try:
        state = run_agent_full(request.user_id, request.query)
    except RuntimeError as e:
        # e.g. Ollama not running
        raise HTTPException(status_code=503, detail=str(e))

    rag_ctx = state.get("rag_context", "")
    kg_ctx = state.get("kg_context", "")
    tool_ctx = state.get("tool_context", "")

    used_rag = bool(rag_ctx) and not rag_ctx.startswith(("RAG index not built", "No relevant"))
    used_kg = bool(kg_ctx) and not kg_ctx.startswith(("No relevant", "Knowledge graph unavailable"))
    used_tool = bool(tool_ctx) and not tool_ctx.startswith("No live tool")

    return ChatResponse(
        answer=state["answer"],
        used_rag=used_rag,
        used_kg=used_kg,
        used_tool=used_tool,
    )


@app.get("/memory/{user_id}", response_model=MemoryResponse)
def get_memory(user_id: str, history_limit: int = 10):
    """Inspect what the system remembers about a given user."""
    prefs = get_preferences(user_id)
    history = get_recent_history(user_id, limit=history_limit)
    return MemoryResponse(preferences=prefs, recent_history=history)


@app.get("/rag/search", response_model=list[RagResult])
def rag_search(q: str, top_k: int = 5):
    """Directly search the RAG vector store (bypasses the full agent)."""
    try:
        results = retrieve(q, top_k=top_k)
    except FileNotFoundError:
        raise HTTPException(
            status_code=503,
            detail="RAG index not built yet. Run: python -m app.rag.build_index",
        )
    return [RagResult(**r) for r in results]


@app.get("/kg/search", response_model=list[KgResult])
def kg_search(entity: str):
    """Directly query the knowledge graph for relationships involving an entity."""
    try:
        results = query_entity(entity)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(status_code=503, detail=f"Knowledge graph unavailable: {e}")
    return [KgResult(**r) for r in results]


# Serve the web UI (landing page + chat interface) as static files.
# Mounted last so it doesn't shadow the API routes above.
app.mount("/ui", StaticFiles(directory="web", html=True, check_dir=False), name="ui")
