"""
Step 7b: FastAPI application.

Exposes the whole system (RAG + Knowledge Graph + Memory + Agent) as a web
API. Run with:

    uvicorn app.api.main:app --reload

Then open http://127.0.0.1:8000/docs for interactive API documentation
(automatically generated by FastAPI).
"""
from fastapi import FastAPI, HTTPException

from app.agent.build_agent import run_agent
from app.api.schemas import ChatRequest, ChatResponse, KgResult, MemoryResponse, RagResult
from app.graph.query_graph import query_entity
from app.memory.memory_store import get_preferences, get_recent_history
from app.rag.retriever import retrieve

app = FastAPI(
    title="Memory-Augmented Chatbot API",
    description=(
        "RAG + Knowledge Graph + Long-Term Memory + LangGraph agent, "
        "exposed as a web API."
    ),
    version="1.0.0",
)


@app.get("/health")
def health_check():
    """Simple liveness check."""
    return {"status": "ok"}


@app.post("/chat", response_model=ChatResponse)
def chat(request: ChatRequest):
    """Send a message to the agent and get a response.
    This runs the full pipeline: memory -> RAG -> knowledge graph ->
    tool routing (if needed) -> generation -> save to memory.
    """
    try:
        answer = run_agent(request.user_id, request.query)
    except RuntimeError as e:
        # e.g. Ollama not running
        raise HTTPException(status_code=503, detail=str(e))
    return ChatResponse(answer=answer)


@app.get("/memory/{user_id}", response_model=MemoryResponse)
def get_memory(user_id: str, history_limit: int = 10):
    """Inspect what the system remembers about a given user."""
    prefs = get_preferences(user_id)
    history = get_recent_history(user_id, limit=history_limit)
    return MemoryResponse(preferences=prefs, recent_history=history)


@app.get("/rag/search", response_model=list[RagResult])
def rag_search(q: str, top_k: int = 5):
    """Directly search the RAG vector store (bypasses the full agent)."""
    try:
        results = retrieve(q, top_k=top_k)
    except FileNotFoundError:
        raise HTTPException(
            status_code=503,
            detail="RAG index not built yet. Run: python -m app.rag.build_index",
        )
    return [RagResult(**r) for r in results]


@app.get("/kg/search", response_model=list[KgResult])
def kg_search(entity: str):
    """Directly query the knowledge graph for relationships involving an entity."""
    try:
        results = query_entity(entity)
    except Exception as e:  # noqa: BLE001
        raise HTTPException(status_code=503, detail=f"Knowledge graph unavailable: {e}")
    return [KgResult(**r) for r in results]
